name: release-main

on:
  release:
    types: [published]

jobs:
{%- if cookiecutter.publish_to_pypi == "y" and cookiecutter.conventional_commits_release == "n" %}
  set-version:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Export tag
        id: vars
        run: {% raw %}echo tag=${GITHUB_REF#refs/*/} >> $GITHUB_OUTPUT{% endraw %}
        if: {% raw %}${{ github.event_name == 'release' }}{% endraw %}

      - name: Update project version
        run: |
          sed -i "s/^version = \".*\"/version = \"$RELEASE_VERSION\"/" pyproject.toml
        env:
          RELEASE_VERSION: {% raw %}${{ steps.vars.outputs.tag }}{% endraw %}
        if: {% raw %}${{ github.event_name == 'release' }}{% endraw %}

      - name: Upload updated pyproject.toml
        uses: actions/upload-artifact@v4
        with:
          name: pyproject-toml
          path: pyproject.toml

  publish:
    runs-on: ubuntu-latest
    needs: [set-version]
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up the environment
        uses: ./.github/actions/setup-python-env

      - name: Download updated pyproject.toml
        uses: actions/download-artifact@v4
        with:
          name: pyproject-toml

      - name: Build package
        run: uv build

      - name: Publish package
        run: uv publish
        env:
          UV_PUBLISH_TOKEN: {% raw %}${{ secrets.PYPI_TOKEN }}{% endraw %}
{% endif %}
{%- if cookiecutter.conventional_commits_release == "y" and cookiecutter.publish_to_pypi == "n" %}
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: python

      - name: Check out
        uses: actions/checkout@v4
        if: {% raw %}${{ steps.release.outputs.releases_created }}{% endraw %}

      - name: Set up the environment
        uses: ./.github/actions/setup-python-env
        if: {% raw %}${{ steps.release.outputs.releases_created }}{% endraw %}

      - name: Download updated pyproject.toml
        uses: actions/download-artifact@v4
        with:
          name: pyproject-toml
        if: {% raw %}${{ steps.release.outputs.releases_created }}{% endraw %}

      - name: Build package
        run: uv build
        if: {% raw %}${{ steps.release.outputs.releases_created }}{% endraw %}

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        if: {% raw %}${{ steps.release.outputs.releases_created }}{% endraw %}
{% endif %}
{%- if cookiecutter.mkdocs == "y" %}
  deploy-docs:
    {%- if cookiecutter.publish_to_pypi == "y" %}
    needs: publish
    {%- endif %}
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up the environment
        uses: ./.github/actions/setup-python-env

      - name: Deploy documentation
        run: uv run mkdocs gh-deploy --force
{% endif %}
